package com.test.portlets.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Employee service. Represents a row in the &quot;Employee_Employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.test.portlets.model.impl.EmployeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.test.portlets.model.impl.EmployeeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Employee
 * @see com.test.portlets.model.impl.EmployeeImpl
 * @see com.test.portlets.model.impl.EmployeeModelImpl
 * @generated
 */
public interface EmployeeModel extends BaseModel<Employee> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a employee model instance should use the {@link Employee} interface instead.
     */

    /**
     * Returns the primary key of this employee.
     *
     * @return the primary key of this employee
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this employee.
     *
     * @param primaryKey the primary key of this employee
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the employee ID of this employee.
     *
     * @return the employee ID of this employee
     */
    public long getEmployeeId();

    /**
     * Sets the employee ID of this employee.
     *
     * @param employeeId the employee ID of this employee
     */
    public void setEmployeeId(long employeeId);

    /**
     * Returns the employee name of this employee.
     *
     * @return the employee name of this employee
     */
    @AutoEscape
    public String getEmployeeName();

    /**
     * Sets the employee name of this employee.
     *
     * @param employeeName the employee name of this employee
     */
    public void setEmployeeName(String employeeName);

    /**
     * Returns the employee gender of this employee.
     *
     * @return the employee gender of this employee
     */
    @AutoEscape
    public String getEmployeeGender();

    /**
     * Sets the employee gender of this employee.
     *
     * @param employeeGender the employee gender of this employee
     */
    public void setEmployeeGender(String employeeGender);

    /**
     * Returns the sb ID of this employee.
     *
     * @return the sb ID of this employee
     */
    public long getSbId();

    /**
     * Sets the sb ID of this employee.
     *
     * @param sbId the sb ID of this employee
     */
    public void setSbId(long sbId);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(Employee employee);

    public int hashCode();

    public CacheModel<Employee> toCacheModel();

    public Employee toEscapedModel();

    public Employee toUnescapedModel();

    public String toString();

    public String toXmlString();
}
