package com.test.portlets.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.test.portlets.model.ManageOrganization;
import com.test.portlets.service.ManageOrganizationLocalService;
import com.test.portlets.service.persistence.ManageOrganizationPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the manage organization local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.test.portlets.service.impl.ManageOrganizationLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.test.portlets.service.impl.ManageOrganizationLocalServiceImpl
 * @see com.test.portlets.service.ManageOrganizationLocalServiceUtil
 * @generated
 */
public abstract class ManageOrganizationLocalServiceBaseImpl
    extends BaseLocalServiceImpl implements ManageOrganizationLocalService,
        IdentifiableBean {
    @BeanReference(type = ManageOrganizationLocalService.class)
    protected ManageOrganizationLocalService manageOrganizationLocalService;
    @BeanReference(type = ManageOrganizationPersistence.class)
    protected ManageOrganizationPersistence manageOrganizationPersistence;
    @BeanReference(type = CounterLocalService.class)
    protected CounterLocalService counterLocalService;
    @BeanReference(type = ResourceLocalService.class)
    protected ResourceLocalService resourceLocalService;
    @BeanReference(type = ResourceService.class)
    protected ResourceService resourceService;
    @BeanReference(type = ResourcePersistence.class)
    protected ResourcePersistence resourcePersistence;
    @BeanReference(type = UserLocalService.class)
    protected UserLocalService userLocalService;
    @BeanReference(type = UserService.class)
    protected UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    private String _beanIdentifier;
    private ClassLoader _classLoader;
    private ManageOrganizationLocalServiceClpInvoker _clpInvoker = new ManageOrganizationLocalServiceClpInvoker();

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link com.test.portlets.service.ManageOrganizationLocalServiceUtil} to access the manage organization local service.
     */

    /**
     * Adds the manage organization to the database. Also notifies the appropriate model listeners.
     *
     * @param manageOrganization the manage organization
     * @return the manage organization that was added
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.REINDEX)
    public ManageOrganization addManageOrganization(
        ManageOrganization manageOrganization) throws SystemException {
        manageOrganization.setNew(true);

        return manageOrganizationPersistence.update(manageOrganization, false);
    }

    /**
     * Creates a new manage organization with the primary key. Does not add the manage organization to the database.
     *
     * @param sbId the primary key for the new manage organization
     * @return the new manage organization
     */
    public ManageOrganization createManageOrganization(long sbId) {
        return manageOrganizationPersistence.create(sbId);
    }

    /**
     * Deletes the manage organization with the primary key from the database. Also notifies the appropriate model listeners.
     *
     * @param sbId the primary key of the manage organization
     * @return the manage organization that was removed
     * @throws PortalException if a manage organization with the primary key could not be found
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.DELETE)
    public ManageOrganization deleteManageOrganization(long sbId)
        throws PortalException, SystemException {
        return manageOrganizationPersistence.remove(sbId);
    }

    /**
     * Deletes the manage organization from the database. Also notifies the appropriate model listeners.
     *
     * @param manageOrganization the manage organization
     * @return the manage organization that was removed
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.DELETE)
    public ManageOrganization deleteManageOrganization(
        ManageOrganization manageOrganization) throws SystemException {
        return manageOrganizationPersistence.remove(manageOrganization);
    }

    public DynamicQuery dynamicQuery() {
        Class<?> clazz = getClass();

        return DynamicQueryFactoryUtil.forClass(ManageOrganization.class,
            clazz.getClassLoader());
    }

    /**
     * Performs a dynamic query on the database and returns the matching rows.
     *
     * @param dynamicQuery the dynamic query
     * @return the matching rows
     * @throws SystemException if a system exception occurred
     */
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery)
        throws SystemException {
        return manageOrganizationPersistence.findWithDynamicQuery(dynamicQuery);
    }

    /**
     * Performs a dynamic query on the database and returns a range of the matching rows.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
     * </p>
     *
     * @param dynamicQuery the dynamic query
     * @param start the lower bound of the range of model instances
     * @param end the upper bound of the range of model instances (not inclusive)
     * @return the range of matching rows
     * @throws SystemException if a system exception occurred
     */
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
        throws SystemException {
        return manageOrganizationPersistence.findWithDynamicQuery(dynamicQuery,
            start, end);
    }

    /**
     * Performs a dynamic query on the database and returns an ordered range of the matching rows.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
     * </p>
     *
     * @param dynamicQuery the dynamic query
     * @param start the lower bound of the range of model instances
     * @param end the upper bound of the range of model instances (not inclusive)
     * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
     * @return the ordered range of matching rows
     * @throws SystemException if a system exception occurred
     */
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
        OrderByComparator orderByComparator) throws SystemException {
        return manageOrganizationPersistence.findWithDynamicQuery(dynamicQuery,
            start, end, orderByComparator);
    }

    /**
     * Returns the number of rows that match the dynamic query.
     *
     * @param dynamicQuery the dynamic query
     * @return the number of rows that match the dynamic query
     * @throws SystemException if a system exception occurred
     */
    public long dynamicQueryCount(DynamicQuery dynamicQuery)
        throws SystemException {
        return manageOrganizationPersistence.countWithDynamicQuery(dynamicQuery);
    }

    public ManageOrganization fetchManageOrganization(long sbId)
        throws SystemException {
        return manageOrganizationPersistence.fetchByPrimaryKey(sbId);
    }

    /**
     * Returns the manage organization with the primary key.
     *
     * @param sbId the primary key of the manage organization
     * @return the manage organization
     * @throws PortalException if a manage organization with the primary key could not be found
     * @throws SystemException if a system exception occurred
     */
    public ManageOrganization getManageOrganization(long sbId)
        throws PortalException, SystemException {
        return manageOrganizationPersistence.findByPrimaryKey(sbId);
    }

    public PersistedModel getPersistedModel(Serializable primaryKeyObj)
        throws PortalException, SystemException {
        return manageOrganizationPersistence.findByPrimaryKey(primaryKeyObj);
    }

    /**
     * Returns a range of all the manage organizations.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
     * </p>
     *
     * @param start the lower bound of the range of manage organizations
     * @param end the upper bound of the range of manage organizations (not inclusive)
     * @return the range of manage organizations
     * @throws SystemException if a system exception occurred
     */
    public List<ManageOrganization> getManageOrganizations(int start, int end)
        throws SystemException {
        return manageOrganizationPersistence.findAll(start, end);
    }

    /**
     * Returns the number of manage organizations.
     *
     * @return the number of manage organizations
     * @throws SystemException if a system exception occurred
     */
    public int getManageOrganizationsCount() throws SystemException {
        return manageOrganizationPersistence.countAll();
    }

    /**
     * Updates the manage organization in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
     *
     * @param manageOrganization the manage organization
     * @return the manage organization that was updated
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.REINDEX)
    public ManageOrganization updateManageOrganization(
        ManageOrganization manageOrganization) throws SystemException {
        return updateManageOrganization(manageOrganization, true);
    }

    /**
     * Updates the manage organization in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
     *
     * @param manageOrganization the manage organization
     * @param merge whether to merge the manage organization with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
     * @return the manage organization that was updated
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.REINDEX)
    public ManageOrganization updateManageOrganization(
        ManageOrganization manageOrganization, boolean merge)
        throws SystemException {
        manageOrganization.setNew(false);

        return manageOrganizationPersistence.update(manageOrganization, merge);
    }

    /**
     * Returns the manage organization local service.
     *
     * @return the manage organization local service
     */
    public ManageOrganizationLocalService getManageOrganizationLocalService() {
        return manageOrganizationLocalService;
    }

    /**
     * Sets the manage organization local service.
     *
     * @param manageOrganizationLocalService the manage organization local service
     */
    public void setManageOrganizationLocalService(
        ManageOrganizationLocalService manageOrganizationLocalService) {
        this.manageOrganizationLocalService = manageOrganizationLocalService;
    }

    /**
     * Returns the manage organization persistence.
     *
     * @return the manage organization persistence
     */
    public ManageOrganizationPersistence getManageOrganizationPersistence() {
        return manageOrganizationPersistence;
    }

    /**
     * Sets the manage organization persistence.
     *
     * @param manageOrganizationPersistence the manage organization persistence
     */
    public void setManageOrganizationPersistence(
        ManageOrganizationPersistence manageOrganizationPersistence) {
        this.manageOrganizationPersistence = manageOrganizationPersistence;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the resource remote service.
     *
     * @return the resource remote service
     */
    public ResourceService getResourceService() {
        return resourceService;
    }

    /**
     * Sets the resource remote service.
     *
     * @param resourceService the resource remote service
     */
    public void setResourceService(ResourceService resourceService) {
        this.resourceService = resourceService;
    }

    /**
     * Returns the resource persistence.
     *
     * @return the resource persistence
     */
    public ResourcePersistence getResourcePersistence() {
        return resourcePersistence;
    }

    /**
     * Sets the resource persistence.
     *
     * @param resourcePersistence the resource persistence
     */
    public void setResourcePersistence(ResourcePersistence resourcePersistence) {
        this.resourcePersistence = resourcePersistence;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    public void afterPropertiesSet() {
        Class<?> clazz = getClass();

        _classLoader = clazz.getClassLoader();

        PersistedModelLocalServiceRegistryUtil.register("com.test.portlets.model.ManageOrganization",
            manageOrganizationLocalService);
    }

    public void destroy() {
        PersistedModelLocalServiceRegistryUtil.unregister(
            "com.test.portlets.model.ManageOrganization");
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    public Object invokeMethod(String name, String[] parameterTypes,
        Object[] arguments) throws Throwable {
        Thread currentThread = Thread.currentThread();

        ClassLoader contextClassLoader = currentThread.getContextClassLoader();

        if (contextClassLoader != _classLoader) {
            currentThread.setContextClassLoader(_classLoader);
        }

        try {
            return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
        } finally {
            if (contextClassLoader != _classLoader) {
                currentThread.setContextClassLoader(contextClassLoader);
            }
        }
    }

    protected Class<?> getModelClass() {
        return ManageOrganization.class;
    }

    protected String getModelClassName() {
        return ManageOrganization.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = manageOrganizationPersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
