package com.test.portlets.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ManageOrganization service. Represents a row in the &quot;ManageOrganization_ManageOrganization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.test.portlets.model.impl.ManageOrganizationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.test.portlets.model.impl.ManageOrganizationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ManageOrganization
 * @see com.test.portlets.model.impl.ManageOrganizationImpl
 * @see com.test.portlets.model.impl.ManageOrganizationModelImpl
 * @generated
 */
public interface ManageOrganizationModel extends BaseModel<ManageOrganization> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a manage organization model instance should use the {@link ManageOrganization} interface instead.
     */

    /**
     * Returns the primary key of this manage organization.
     *
     * @return the primary key of this manage organization
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this manage organization.
     *
     * @param primaryKey the primary key of this manage organization
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the sb ID of this manage organization.
     *
     * @return the sb ID of this manage organization
     */
    public long getSbId();

    /**
     * Sets the sb ID of this manage organization.
     *
     * @param sbId the sb ID of this manage organization
     */
    public void setSbId(long sbId);

    /**
     * Returns the sb name of this manage organization.
     *
     * @return the sb name of this manage organization
     */
    @AutoEscape
    public String getSbName();

    /**
     * Sets the sb name of this manage organization.
     *
     * @param sbName the sb name of this manage organization
     */
    public void setSbName(String sbName);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(ManageOrganization manageOrganization);

    public int hashCode();

    public CacheModel<ManageOrganization> toCacheModel();

    public ManageOrganization toEscapedModel();

    public ManageOrganization toUnescapedModel();

    public String toString();

    public String toXmlString();
}
